coverage:
  status:
    project:
      default:
        target: auto
        flags:
          - total
    patch:
      default:
        only_pulls: true
        flags:
          - total

flags:
  total:
    paths:
      - .*
    carryforward: true
