codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 70...100

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: reach,diff,flags,files,footer
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true

ignore:
  - "**/test"

fixes:
  - "autoware.universe/*/accel_brake_map_calibrator/::"
  - "autoware.universe/*/ad_service_state_monitor/::"
  - "autoware.universe/*/autoware_auto_cmake/::"
  - "autoware.universe/*/autoware_auto_common/::"
  - "autoware.universe/*/autoware_auto_control_msgs/::"
  - "autoware.universe/*/autoware_auto_geometry/::"
  - "autoware.universe/*/autoware_auto_geometry_msgs/::"
  - "autoware.universe/*/autoware_auto_mapping_msgs/::"
  - "autoware.universe/*/autoware_auto_msgs/::"
  - "autoware.universe/*/autoware_auto_perception_msgs/::"
  - "autoware.universe/*/autoware_auto_perception_rviz_plugin/::"
  - "autoware.universe/*/autoware_auto_planning_msgs/::"
  - "autoware.universe/*/autoware_auto_system_msgs/::"
  - "autoware.universe/*/autoware_auto_tf2/::"
  - "autoware.universe/*/autoware_auto_vehicle_msgs/::"
  - "autoware.universe/*/autoware_lint_common/::"
  - "autoware.universe/*/autoware_point_types/::"
  - "autoware.universe/*/autoware_testing/::"
  - "autoware.universe/*/behavior_path_planner/::"
  - "autoware.universe/*/behavior_velocity_planner/::"
  - "autoware.universe/*/compare_map_segmentation/::"
  - "autoware.universe/*/control_performance_analysis/::"
  - "autoware.universe/*/costmap_generator/::"
  - "autoware.universe/*/detected_object_feature_remover/::"
  - "autoware.universe/*/detection_by_tracker/::"
  - "autoware.universe/*/dummy_diag_publisher/::"
  - "autoware.universe/*/dummy_infrastructure/::"
  - "autoware.universe/*/dummy_perception_publisher/::"
  - "autoware.universe/*/ekf_localizer/::"
  - "autoware.universe/*/elevation_map_loader/::"
  - "autoware.universe/*/emergency_handler/::"
  - "autoware.universe/*/euclidean_cluster/::"
  - "autoware.universe/*/external_cmd_converter/::"
  - "autoware.universe/*/external_cmd_selector/::"
  - "autoware.universe/*/external_velocity_limit_selector/::"
  - "autoware.universe/*/fake_test_node/::"
  - "autoware.universe/*/fault_injection/::"
  - "autoware.universe/*/freespace_planner/::"
  - "autoware.universe/*/freespace_planning_algorithms/::"
  - "autoware.universe/*/geo_pos_conv/::"
  - "autoware.universe/*/global_parameter_loader/::"
  - "autoware.universe/*/gnss_poser/::"
  - "autoware.universe/*/goal_distance_calculator/::"
  - "autoware.universe/*/grid_map/::"
  - "autoware.universe/*/grid_map_cmake_helpers/::"
  - "autoware.universe/*/grid_map_core/::"
  - "autoware.universe/*/grid_map_costmap_2d/::"
  - "autoware.universe/*/grid_map_cv/::"
  - "autoware.universe/*/grid_map_demos/::"
  - "autoware.universe/*/grid_map_filters/::"
  - "autoware.universe/*/grid_map_loader/::"
  - "autoware.universe/*/grid_map_msgs/::"
  - "autoware.universe/*/grid_map_octomap/::"
  - "autoware.universe/*/grid_map_pcl/::"
  - "autoware.universe/*/grid_map_ros/::"
  - "autoware.universe/*/grid_map_rviz_plugin/::"
  - "autoware.universe/*/grid_map_sdf/::"
  - "autoware.universe/*/grid_map_visualization/::"
  - "autoware.universe/*/ground_segmentation/::"
  - "autoware.universe/*/gyro_odometer/::"
  - "autoware.universe/*/had_map_utils/::"
  - "autoware.universe/*/image_transport_decompressor/::"
  - "autoware.universe/*/imu_corrector/::"
  - "autoware.universe/*/initial_pose_button_panel/::"
  - "autoware.universe/*/interpolation/::"
  - "autoware.universe/*/joy_controller/::"
  - "autoware.universe/*/kalman_filter/::"
  - "autoware.universe/*/lane_departure_checker/::"
  - "autoware.universe/*/lanelet2_extension/::"
  - "autoware.universe/*/laserscan_to_occupancy_grid_map/::"
  - "autoware.universe/*/lidar_apollo_instance_segmentation/::"
  - "autoware.universe/*/lidar_centerpoint/::"
  - "autoware.universe/*/livox_tag_filter/::"
  - "autoware.universe/*/localization_error_monitor/::"
  - "autoware.universe/*/map_based_prediction/::"
  - "autoware.universe/*/map_loader/::"
  - "autoware.universe/*/map_tf_generator/::"
  - "autoware.universe/*/mission_planner/::"
  - "autoware.universe/*/motion_common/::"
  - "autoware.universe/*/motion_testing/::"
  - "autoware.universe/*/motion_velocity_smoother/::"
  - "autoware.universe/*/multi_object_tracker/::"
  - "autoware.universe/*/mussp/::"
  - "autoware.universe/*/ndt/::"
  - "autoware.universe/*/ndt_omp/::"
  - "autoware.universe/*/ndt_pcl_modified/::"
  - "autoware.universe/*/ndt_scan_matcher/::"
  - "autoware.universe/*/object_merger/::"
  - "autoware.universe/*/object_range_splitter/::"
  - "autoware.universe/*/obstacle_avoidance_planner/::"
  - "autoware.universe/*/obstacle_collision_checker/::"
  - "autoware.universe/*/obstacle_stop_planner/::"
  - "autoware.universe/*/occupancy_grid_map_outlier_filter/::"
  - "autoware.universe/*/osqp_interface/::"
  - "autoware.universe/*/pacmod_interface/::"
  - "autoware.universe/*/path_distance_calculator/::"
  - "autoware.universe/*/planning_error_monitor/::"
  - "autoware.universe/*/pointcloud_preprocessor/::"
  - "autoware.universe/*/polar_grid/::"
  - "autoware.universe/*/pose2twist/::"
  - "autoware.universe/*/pose_initializer/::"
  - "autoware.universe/*/pure_pursuit/::"
  - "autoware.universe/*/raw_vehicle_cmd_converter/::"
  - "autoware.universe/*/roi_cluster_fusion/::"
  - "autoware.universe/*/route_handler/::"
  - "autoware.universe/*/scenario_selector/::"
  - "autoware.universe/*/shape_estimation/::"
  - "autoware.universe/*/shift_decider/::"
  - "autoware.universe/*/signal_processing/::"
  - "autoware.universe/*/simple_planning_simulator/::"
  - "autoware.universe/*/stop_filter/::"
  - "autoware.universe/*/surround_obstacle_checker/::"
  - "autoware.universe/*/system_error_monitor/::"
  - "autoware.universe/*/system_monitor/::"
  - "autoware.universe/*/tensorrt_yolo/::"
  - "autoware.universe/*/tier4_api_msgs/::"
  - "autoware.universe/*/tier4_api_utils/::"
  - "autoware.universe/*/tier4_auto_msgs_converter/::"
  - "autoware.universe/*/tier4_autoware_launch/::"
  - "autoware.universe/*/tier4_autoware_utils/::"
  - "autoware.universe/*/tier4_calibration_rviz_plugin/::"
  - "autoware.universe/*/tier4_control_launch/::"
  - "autoware.universe/*/tier4_control_msgs/::"
  - "autoware.universe/*/tier4_datetime_rviz_plugin/::"
  - "autoware.universe/*/tier4_debug_msgs/::"
  - "autoware.universe/*/tier4_debug_tools/::"
  - "autoware.universe/*/tier4_external_api_msgs/::"
  - "autoware.universe/*/tier4_hmi_msgs/::"
  - "autoware.universe/*/tier4_integration_launch/::"
  - "autoware.universe/*/tier4_localization_launch/::"
  - "autoware.universe/*/tier4_localization_msgs/::"
  - "autoware.universe/*/tier4_localization_rviz_plugin/::"
  - "autoware.universe/*/tier4_map_launch/::"
  - "autoware.universe/*/tier4_pcl_extensions/::"
  - "autoware.universe/*/tier4_perception_launch/::"
  - "autoware.universe/*/tier4_perception_msgs/::"
  - "autoware.universe/*/tier4_perception_rviz_plugin/::"
  - "autoware.universe/*/tier4_planning_launch/::"
  - "autoware.universe/*/tier4_planning_msgs/::"
  - "autoware.universe/*/tier4_planning_rviz_plugin/::"
  - "autoware.universe/*/tier4_sensing_launch/::"
  - "autoware.universe/*/tier4_simulation_msgs/::"
  - "autoware.universe/*/tier4_simulator_launch/::"
  - "autoware.universe/*/tier4_state_rviz_plugin/::"
  - "autoware.universe/*/tier4_system_launch/::"
  - "autoware.universe/*/tier4_system_msgs/::"
  - "autoware.universe/*/tier4_v2x_msgs/::"
  - "autoware.universe/*/tier4_vehicle_launch/::"
  - "autoware.universe/*/tier4_vehicle_msgs/::"
  - "autoware.universe/*/tier4_vehicle_rviz_plugin/::"
  - "autoware.universe/*/time_utils/::"
  - "autoware.universe/*/topic_state_monitor/::"
  - "autoware.universe/*/traffic_light_classifier/::"
  - "autoware.universe/*/traffic_light_map_based_detector/::"
  - "autoware.universe/*/traffic_light_ssd_fine_detector/::"
  - "autoware.universe/*/traffic_light_visualization/::"
  - "autoware.universe/*/trajectory_follower/::"
  - "autoware.universe/*/trajectory_follower_nodes/::"
  - "autoware.universe/*/vehicle_cmd_gate/::"
  - "autoware.universe/*/vehicle_constants_manager/::"
  - "autoware.universe/*/vehicle_info_util/::"
  - "autoware.universe/*/vehicle_velocity_converter/::"
  - "autoware.universe/*/velodyne_monitor/::"
  - "autoware.universe/*/web_controller/::"
