name: build-and-test-pr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:galactic
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@tier4/proposal

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@tier4/proposal
        with:
          rosdistro: galactic

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@tier4/proposal

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: KeisukeShima/autoware-github-actions/colcon-build@feature/coverage-flags
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos

      - name: Test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: KeisukeShima/autoware-github-actions/colcon-test@feature/coverage-flags
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos

  labeled-test:
    runs-on: ubuntu-latest
    container: ros:galactic
    needs: build
    strategy:
      matrix:
        label: [gtest, smoke_test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@tier4/proposal

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@tier4/proposal
        with:
          rosdistro: galactic

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@tier4/proposal

      - name: Labeled test
        id: labeled-test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: KeisukeShima/autoware-github-actions/colcon-test@feature/coverage-flags
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos
          label: ${{ matrix.label }}

      - name: Check files
        run: |
          ls -l
          echo ${{ steps.labeled-test.outputs.coverage-reports }}

      - name: Upload coverage to Codecov
        if: ${{ steps.labeled-test.outputs.coverage-reports != '' }}
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.labeled-test.outputs.coverage-reports }}
          fail_ci_if_error: true
          verbose: true
          flags: ${{ matrix.label }}

  clang-tidy:
    runs-on: ubuntu-latest
    container: ros:galactic
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@tier4/proposal

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@tier4/proposal
        with:
          rosdistro: galactic

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@tier4/proposal

      - name: Run clang-tidy
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/tier4/proposal/.clang-tidy
          build-depends-repos: build_depends.repos
