name: build-and-test-pr

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:galactic

    steps:
      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@feature/composite-action

      - name: Get modified source files
        id: get-modified-source-files
        uses: autowarefoundation/autoware-github-actions/get-modified-source-files@feature/composite-action

      - name: Build and test
        id: build-and-test
        uses: autowarefoundation/autoware-github-actions/colcon-build-and-test@feature/composite-action
        with:
          rosdistro: galactic
          build-depends-repos: build_depends.repos
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}

      - name: Run clang-tidy
        if: ${{ steps.get-modified-source-files.outputs.modified-source-files }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@feature/composite-action
        with:
          rosdistro: galactic
          build-depends-repos: build_depends.repos
          target-files: ${{ steps.get-modified-source-files.outputs.modified-source-files }}
          compile-commands-hash: ${{ steps.build-and-test.outputs.compile-commands-hash }}
