name: spell-check

on:
  pull_request:

jobs:
  spell-check:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/spell-check.yaml@feature/composite-action
    with:
      cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
